config/routes.rb
Learning::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new,    :create,  :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup',   to: 'users#new',            via: 'get'   
  match '/signin',   to: 'sessions#new',         via: 'get'
  match '/signout',  to: 'sessions#destroy',     via: 'delete'
  match '/help',     to: 'static_pages#help',    via: 'get'
  match '/about',    to: 'static_pages#about',   via: 'get'
  match '/contact',  to: 'static_pages#contact', via: 'get'
end

app/views/layouts/_footer.html.haml
.legal.pure-g-r
  .pure-u-2-5
    .l-box
      %p.legal-license
        This site is built with &lt;3 using Pure Sass
      %p.legal-license
        I don't like legal stuff
  .pure-u-1-5
    %p.l-centered
      \&copy; 2013 Theron Boerner
  .pure-u-2-5
    .l-box
      %ul.legal-links.pure-g
        %li.pure-u-1-2
          = render 'layouts/github_star'
        %li
        %p       
          = render 'layouts/twitter'

app/views/layouts/_github_star.html.haml
%iframe{:allowtransparency => "true", :frameborder => "0", :height => "20", :scrolling => "0", :src => "http://ghbtns.com/github-btn.html?user=hunterboerner&repo=learning&type=watch", :width => "62"}

app/views/layouts/_header.html.haml
#horizontal-menu.pure-menu.pure-menu-open.pure-menu-fixed.pure-menu-horizontal
    %a.pure-menu-heading{:href => root_path} 
        .red
            Sample App
    %ul
        %li= link_to "Home", root_path
        %li= link_to "Help", help_path
        - if signed_in?
            %li= link_to "Sign out", signout_path, method: "delete"
            %li= link_to "Users", users_path
            %li= link_to "Profile", current_user
            %li= link_to "Settings", edit_user_path(current_user)
        - else
            %li= link_to "Sign in", signin_path
        %li= link_to "Contact", contact_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/_twitter.html.haml
<a href="https://twitter.com/hunterboerner" class="twitter-follow-button" data-size="small">Follow</a>
<script src="//platform.twitter.com/widgets.js"></script>

app/views/layouts/application.html.haml
!!! 5
%html
    %head 
        %title= full_title(yield(:title))
         
        = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
        = javascript_include_tag "application", "data-turbolinks-track" => true
        = csrf_meta_tags
        = render 'layouts/shim'
    %body
        .content
            .header
                = render 'layouts/header'
                - flash.each do |key, value|
                    = content_tag(:div, value, class: "alert alert-#{key}")
            = yield
            = render 'layouts/footer'
            = debug(params) if Rails.env.development?